redis:
  image: redis:5.0.6
  volumes:
    - ./redis/data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - "6379:6379"

mysql:
  image: mysql:5.7.28
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=3426
    - MYSQL_DATABASE=intctrl_db
    - MYSQL_USER=intctrl_db
    - MYSQL_PASSWORD=intctrl_db
  ports:
    - "3306:3306"

teamcity:
  image: jetbrains/teamcity-server:2019.1.5
  links:
    - neu-mysql
  volumes:
    - ./teamcity/data:/data/teamcity_server/datadir
    - ./teamcity/logs:/opt/teamcity/logs
  environment:
    - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m
  ports:
    - "8111:8111"

nexus:
  image: sonatype/nexus3
  volumes:
    - ./nexus/data:/nexus-data
  ports:
    - "8081:8081"