redis:
  image: redis:5.0.6
  volumes:
    - ./redis/data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - "6379:6379"

mysql:
  image: mysql:5.7.34
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=3426
    - MYSQL_DATABASE=ah
    - MYSQL_USER=ah
    - MYSQL_PASSWORD=ah
  ports:
    - "3306:3306"

youtrack:
  image: jetbrains/youtrack:2021.3.30245
  volumes:
    - ./youtrack/data:/opt/youtrack/data
    - ./youtrack/conf:/opt/youtrack/conf
    - ./youtrack/logs:/opt/youtrack/logs
    - ./youtrack/backups:/opt/youtrack/backups
  ports:
    - "8080:8080"

teamcity-server:
  image: jetbrains/teamcity-server:2021.2
  links:
    - mysql
  volumes:
    - ./teamcity/server/data:/data/teamcity_server/datadir
    - ./teamcity/server/logs:/opt/teamcity/logs
    - ./teamcity/server/entrypoint.sh:/entrypoint.sh
  environment:
    # Modify as will
    - MYSQL_DRIVER_URL=https://repo.gradle.org/gradle/libs/mysql/mysql-connector-java/5.1.48/mysql-connector-java-5.1.48.jar
    - TEAMCITY_CONTEXT=teamcity
    - TEAMCITY_DATA_PATH=/data/teamcity_server/datadir
    - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m
  entrypoint: /entrypoint.sh
  ports:
    - "8111:8111"

teamcity-agent:
  image: jetbrains/teamcity-agent:2021.2
  links:
    - redis
    - teamcity-server
  environment:
    - SERVER_URL=http://teamcity-server:8111/teamcity

jenkins:
  image: alphahinex/compose-docker:jenkins-lts
  ports:
    - "8080:8080"
    - "50000:50000"

nexus:
  image: sonatype/nexus3:3.20.1
  volumes:
    - ./nexus/data:/nexus-data
  ports:
    - "8081:8081"

nacos:
  image: nacos/nacos-server:1.1.4
  environment:
    - MODE=standalone
  ports:
    - "8848:8848"

gitlab:
  image: gitlab/gitlab-ce:12.8.1-ce.0
  volumes:
    - ./gitlab/opt:/var/opt/gitlab
    - ./gitlab/log:/var/log/gitlab
    - ./gitlab/etc:/etc/gitlab
  # Use external_url to modify the container id in clone path
  # environment:
  #   GITLAB_OMNIBUS_CONFIG: |
  #     external_url 'http://192.168.16.100:7780'
  #     prometheus_monitoring['enable'] = false
  ports:
    - "7780:7780"
    - "7443:443"
    - "7722:22"

nginx:
  image: nginx:1.17.9
  volumes:
    - ./nginx:/usr/share/nginx/file_server
    - ./nginx/file_server.conf:/etc/nginx/conf.d/file_server.conf
    - ./nginx/pwd:/etc/nginx/pwd
    - ./nginx:/usr/share/nginx/fb_sep
    - ./nginx/fb_sep.conf:/etc/nginx/conf.d/fb_sep.conf
  ports:
    - "2020:2020"
    - "8000:8000"

zoo:
  image: zookeeper:3.6.1
  ports:
    - 2181:2181

sonar:
  image: sonarqube:7.9.5-community
  ports:
    - 9000:9000

mongo:
  image: mongo:4.4.23
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
  ports:
    - 27017:27017
