FROM jetbrains/teamcity-server:2020.2
MAINTAINER Alpha Hinex <AlphaHinex@gmail.com>

RUN curl --create-dirs -o $TEAMCITY_DATA_PATH/lib/jdbc/mysql-connector-java-5.1.49.jar https://repo.gradle.org/gradle/libs/mysql/mysql-connector-java/5.1.49/mysql-connector-java-5.1.49.jar
